version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./Dockerfile.production
    env_file:
      - environment/.production.env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - backend_prod
    command: npm run start:prod
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - environment/.production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_prod
    restart: always

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: evgenykolotov
      MINIO_ROOT_PASSWORD: Kolot4229
    volumes:
      - minio-storage:/data
    networks:
      - backend_prod
    restart: always

volumes:
  pgdata:
  minio-storage:

networks:
  backend_prod:
    name: cloud_drive_network